[package]
name = "syndicate_starknet"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra = true
casm = true

[dependencies]
starknet = "2.8.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
