/**
 * STACKS PROTOCOL - Bridge Integration
 * 
 * ENHANCEMENT FIRST: Extends existing bridge architecture
 * - DRY: Single source of truth via Chainhook → Attestation → Proxy
 * - CLEAN: Clear separation - Attestation/CCTP handles bridging, Proxy handles purchase
 * - MODULAR: Implements BridgeProtocol interface for unified management
 * - CONSOLIDATION: Migrating from operator-based to fully decentralized
 * 
 * Architecture:
 * 1. User calls Stacks contract → locks/burns USDCx → emits attestation intent
 * 2. Chainhook detects event → POST to /api/chainhook
 * 3. Attestation service (Stacks/Circle xReserve) confirms → CCTP relays to Base
 * 4. Proxy receives USDC → executes Megapot purchase atomically
 * 5. Status tracked via /api/purchase-status/[txId]
 * 
 * Decentralization:
 * - Uses Circle xReserve + CCTP (attestation-based, no operator)
 * - NO OPERATOR KEY REQUIRED
 * - Fully decentralized via attestation services
 */

import type {
    BridgeProtocol,
    BridgeParams,
    BridgeResult,
    ProtocolHealth,
    ChainIdentifier,
    BridgeStatus,
} from '../types';
import { BridgeError, BridgeErrorCode } from '../types';

// ============================================================================
// STACKS BRIDGE PROTOCOL
// ============================================================================

export class StacksProtocol implements BridgeProtocol {
    readonly name = 'stacks' as const;

    // Health tracking
    private successCount = 0;
    private failureCount = 0;
    private totalTimeMs = 0;
    private lastFailure?: Date;

    // ============================================================================
    // BridgeProtocol Interface Implementation
    // ============================================================================

    supports(sourceChain: ChainIdentifier, destinationChain: ChainIdentifier): boolean {
        // Stacks → Base only
        return sourceChain === 'stacks' && destinationChain === 'base';
    }

    async estimate(params: BridgeParams) {
        return {
            fee: '0.50',
            timeMs: 180_000,
            gasEstimate: 'Included in attestation/CCTP',
        };
    }

    async bridge(params: BridgeParams): Promise<BridgeResult> {
        const startTime = Date.now();

        try {
            // Validate parameters
            const validation = await this.validate(params);
            if (!validation.valid) {
                throw new BridgeError(
                    BridgeErrorCode.INVALID_ADDRESS,
                    validation.error || 'Invalid parameters',
                    'stacks'
                );
            }

            params.onStatus?.('validating', { protocol: 'stacks' });

            const result: BridgeResult = {
                success: true,
                protocol: 'stacks',
                status: 'pending_signature' as BridgeStatus,
                bridgeId: `stacks-attestation-${Date.now()}`,
                estimatedTimeMs: 180_000,
                details: {
                    message: 'Sign Stacks contract transaction to initiate USDCx attestation and CCTP relay.',
                    sourceChain: params.sourceChain,
                    destinationChain: params.destinationChain,
                    amount: params.amount,
                    recipient: params.destinationAddress,
                    steps: [
                        '1. Sign Stacks transaction (burns/locks USDCx)',
                        '2. Attestation generated by Stacks/Circle',
                        '3. CCTP relays to Base',
                        '4. Proxy executes ticket purchase',
                    ],
                },
            };

            // Update health metrics
            if (result.success) {
                this.successCount++;
                this.totalTimeMs += Date.now() - startTime;
            } else {
                this.failureCount++;
                this.lastFailure = new Date();
            }

            return result;

        } catch (error) {
            this.failureCount++;
            this.lastFailure = new Date();

            console.error('[StacksProtocol] Bridge failed:', error);

            return {
                success: false,
                protocol: 'stacks',
                status: 'failed',
                error: error instanceof Error ? error.message : 'Unknown error',
                errorCode: error instanceof BridgeError ? error.code : BridgeErrorCode.UNKNOWN,
            };
        }
    }

    async getHealth(): Promise<ProtocolHealth> {
        const total = this.successCount + this.failureCount;
        const successRate = total > 0 ? this.successCount / total : 0.95;
        const averageTimeMs = this.successCount > 0 ? this.totalTimeMs / this.successCount : 180_000;

        return {
            protocol: 'stacks',
            isHealthy: true,
            successRate,
            averageTimeMs,
            consecutiveFailures: this.failureCount,
            estimatedFee: '0.50',
            statusDetails: {
                recentFailures: this.failureCount > 3,
            }
        };
    }

    async validate(params: BridgeParams): Promise<{ valid: boolean; error?: string }> {
        if (params.sourceChain !== 'stacks' || params.destinationChain !== 'base') {
            return { valid: false, error: 'Unsupported route for Stacks protocol' };
        }
        if (!params.destinationAddress || !params.destinationAddress.startsWith('0x') || params.destinationAddress.length !== 42) {
            return { valid: false, error: 'Invalid destination EVM address' };
        }
        if (!params.amount || Number(params.amount) <= 0) {
            return { valid: false, error: 'Invalid amount' };
        }
        return { valid: true };
    }
}

// ============================================================================
// SINGLETON EXPORT (following existing pattern)
// ============================================================================

export const stacksProtocol = new StacksProtocol();
